### ISSUE TITLE
Not support in Laravel 5.2

### ISSUE THREAD

**Issue by tronghiep92** [TerbiumLibs/dbConfig#10]
Hi,
I install package for Laravel 5.2  and was error.
`don't install illuminate/support v5.1.2|don't install laravel/framework v5.2.0`

Thanks!!

**Comment by mikhalkov5** [comment]
same issue :(

Problem 1
    - Installation request for terbium/db-config 2.0.1 -> satisfiable by terbium/db-config[2.0.1].
    - Conclusion: remove laravel/framework v5.2.9
    - terbium/db-config 2.0.1 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.2.9
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.2.9
    - don't install illuminate/support v5.1.16|don't install laravel/framework v5.2.9
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5.2.9
    - don't install illuminate/support v5.1.20|don't install laravel/framework v5.2.9
    - don't install illuminate/support v5.1.22|don't install laravel/framework v5.2.9
    - don't install illuminate/support v5.1.25|don't install laravel/framework v5.2.9
    - don't install illuminate/support v5.1.28|don't install laravel/framework v5.2.9
    - don't install illuminate/support v5.1.30|don't install laravel/framework v5.2.9
    - don't install illuminate/support v5.1.31|don't install laravel/framework v5.2.9
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5.2.9
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.2.9
    - Installation request for laravel/framework 5.2.9 -> satisfiable by laravel/framework[v5.2.9].

**Comment by KuenzelIT** [comment]
I am using a fork, which does support 5.2:
https://github.com/amida-software/dbConfig/network

You can replace the main repository like this in your composer.php:

```
"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "terbium/db-config": "dev-master",
    },
"repositories": [
        {
            "url": "https://github.com/amida-software/dbConfig",
            "type": "git"
        }
    ]
```

Make sure you get `dev-master` for `terbium/db-config` to get the source from the fork.

**Comment by KuenzelIT** [comment]
Thanks to @yaapis the main repo should now be compatible to Laravel > 5.1 .

So this issue can be closed.
