### ISSUE TITLE
Change requirements in packagist to support new laravel versions

### ISSUE THREAD

**Issue by KuenzelIT** [TerbiumLibs/dbConfig#12]
Hey,

after adding the compatibility in the repo, do the changes automatically get into packagist too? Or does the author need to change the requirements there?

https://packagist.org/packages/terbium/db-config

I hope to be able to switch to the main repo soon. Currently composer still tells me:
`    - terbium/db-config 2.0.0 requires illuminate/support 5.1.* -> satisfiable by ...`

Thanks!

**Comment by yaapis** [comment]
>  do the changes automatically get into packagist too
Yes, but in dev-master branch.
I made 2.0.2 release - https://packagist.org/packages/terbium/db-config#2.0.2
