### ISSUE TITLE
Laravel 5?

### ISSUE THREAD

**Issue by KuenzelIT** [TerbiumLibs/dbConfig#5]
Hey,
I'm using this package in Laravel 4 right now and may be upgrading soon. Does this package support Laravel 5? (I assume yes, but just to make sure....)

Thanks!

**Comment by yaapis** [comment]
Not yet (In fact - I had no time to port this package to L5). But I'll keep an eye on this feature and will check L5 compability asap

**Comment by TheDigitalOrchard** [comment]
The README says to use the 2.* branch for L5, but no such branch exists. I then assume that 2.* was merged into the Master branch, yet the documented installation steps do not work in their entirety. For example, the migrations won't run, as documented.

This forum discussion explains how to get package migrations to work with L5, and I'll submit a pull request if this is not yet implemented in DbConfig.

http://laravel.io/forum/01-08-2015-package-migrations-not-working-in-laravel-5

**Comment by Debeet** [comment]
I'm also interested in this mysterious 2.* branch :)

**Comment by yaapis** [comment]
Excuse me guys for waiting =)
https://github.com/TerbiumLibs/dbConfig/releases/tag/2.0.0

**Comment by Debeet** [comment]
Better late than ever as they say :+1: Thanks!
